var config = require('config');
var dbbase=require('../../models/db/'+config.get('db.server')+'/functions').poolDatabase;

exports.query    = {

    getBillOffer       : function(data,cb){dbbase.getBillOffer(data,function(row){return cb(row);});},
    getBillOfferDetail       : function(data,cb){dbbase.getBillOfferDetail(data,function(row){return cb(row);});},
    getBillOfferAdditional       : function(data,cb){dbbase.getBillOfferAdditional(data,function(row){return cb(row);});},
    getOfferVen        : function(data,cb){dbbase.getOfferVen(data,function(row){return cb(row);});},
    getEnquiryVen      : function(data,cb){dbbase.getEnquiryVen(data,function(row){return cb(row);});},
    getofferEnquiryVen : function(data,cb){dbbase.getofferEnquiryVen(data,function(row){return cb(row);});},
    getOfferDetails : function(data,cb){dbbase.getOfferDetails(data,function(row){return cb(row);});},
    getworkorderVen : function(data,cb){dbbase.getworkorderVen(data,function(row){return cb(row);});},
    getPlanVen : function(data,cb){dbbase.getPlanVen(data,function(row){return cb(row);});},
    getMonthlyPlansheetVen : function(data,cb){dbbase.getMonthlyPlansheetVen(data,function(row){return cb(row);});},
    getprodspecificationVen : function(data,cb){dbbase.getprodspecificationVen(data,function(row){return cb(row);});},
    getproditemspecificationVen : function(data,cb){dbbase.getproditemspecificationVen(data,function(row){return cb(row);});},
    getprodfeatureVen : function(data,cb){dbbase.getprodfeatureVen(data,function(row){return cb(row);});},
    getproditemcodificationVen : function(data,cb){dbbase.getproditemcodificationVen(data,function(row){return cb(row);});},
    getrawitemVen : function(data,cb){dbbase.getrawitemVen(data,function(row){return cb(row);});},
    getserviceitemVen : function(data,cb){dbbase.getserviceitemVen(data,function(row){return cb(row);});},
    getsalesagentVen : function(data,cb){dbbase.getsalesagentVen(data,function(row){return cb(row);});},
    getcomponentcategoryVen : function(data,cb){dbbase.getcomponentcategoryVen(data,function(row){return cb(row);});},
    getsubcomponentcategoryVen : function(data,cb){dbbase.getsubcomponentcategoryVen(data,function(row){return cb(row);});},
    getsubfeatureVen : function(data,cb){dbbase.getsubfeatureVen(data,function(row){return cb(row);});},
    getunitVen : function(data,cb){dbbase.getunitVen(data,function(row){return cb(row);});},
    getAssetVen : function(data,cb){dbbase.getAssetVen(data,function(row){return cb(row);});},
    getOfferEdit       : function(data,cb){dbbase.getOfferEdit(data,function(row){return cb(row);});},
    getEnquiryEdit       : function(data,cb){dbbase.getEnquiryEdit(data,function(row){return cb(row);});},
    getworkorderEdit       : function(data,cb){dbbase.getworkorderEdit(data,function(row){return cb(row);});},
    getCommercialworkorder       : function(data,cb){dbbase.getCommercialworkorder(data,function(row){return cb(row);});},
    getOfferproductEdit    : function(data,cb){dbbase.getOfferproductEdit(data,function(row){return cb(row);});},
    getAssetEdit    : function(data,cb){dbbase.getAssetEdit(data,function(row){return cb(row);});},
    getAssettypeVen    : function(data,cb){dbbase.getAssettypeVen(data,function(row){return cb(row);});},
    ckDuplicateCustomerCompany       : function(data,cb){dbbase.ckDuplicateCustomerCompany(data,function(row){return cb(row);});},
    ckDuplicateCode       : function(data,cb){dbbase.ckDuplicateCode(data,function(row){return cb(row);});},
    reportplanningsummaryDet       : function(data,cb){dbbase.reportplanningsummaryDet(data,function(row){return cb(row);});},
    reportplancomponentDet       : function(data,cb){dbbase.reportplancomponentDet(data,function(row){return cb(row);});},
    reportenquirybycusDet       : function(data,cb){dbbase.reportenquirybycusDet(data,function(row){return cb(row);});},
    reportallenquiryDet       : function(data,cb){dbbase.reportallenquiryDet(data,function(row){return cb(row);});},
    reportofferDet       : function(data,cb){dbbase.reportofferDet(data,function(row){return cb(row);});},
    reportwobystatusDate       : function(data,cb){dbbase.reportwobystatusDate(data,function(row){return cb(row);});},
    reportallwoDate       : function(data,cb){dbbase.reportallwoDate(data,function(row){return cb(row);});},
    getprodcodedetails       : function(data,cb){dbbase.getprodcodedetails(data,function(row){return cb(row);});},
    reportalldepincomeDet       : function(data,cb){dbbase.reportalldepincomeDet(data,function(row){return cb(row);});},
    reportalldepcompanyDet       : function(data,cb){dbbase.reportalldepcompanyDet(data,function(row){return cb(row);});},
    getAssetPartnerVen       : function(data,cb){dbbase.getAssetPartnerVen(data,function(row){return cb(row);});},
    getAssetlocationVen       : function(data,cb){dbbase.getAssetlocationVen(data,function(row){return cb(row);});},
    getAcureAssetVen       : function(data,cb){dbbase.getAcureAssetVen(data,function(row){return cb(row);});},
    getAcureAssetEdit       : function(data,cb){dbbase.getAcureAssetEdit(data,function(row){return cb(row);});},
    getIssueAssetVen       : function(data,cb){dbbase.getIssueAssetVen(data,function(row){return cb(row);});},
    getIssueAssetEdit       : function(data,cb){dbbase.getIssueAssetEdit(data,function(row){return cb(row);});},
    getReturnAssetVen       : function(data,cb){dbbase.getReturnAssetVen(data,function(row){return cb(row);});},
    getReturnAssetEdit       : function(data,cb){dbbase.getReturnAssetEdit(data,function(row){return cb(row);});},
    getReqPlanVen       : function(data,cb){dbbase.getReqPlanVen(data,function(row){return cb(row);});},
    getReqPurchaseVen       : function(data,cb){dbbase.getReqPurchaseVen(data,function(row){return cb(row);});},
    getReqDetailsPurchaseVen       : function(data,cb){dbbase.getReqDetailsPurchaseVen(data,function(row){return cb(row);});},
    getPurchaseEnquiryVen       : function(data,cb){dbbase.getPurchaseEnquiryVen(data,function(row){return cb(row);});},
    getPurchaseEnquiryEdit       : function(data,cb){dbbase.getPurchaseEnquiryEdit(data,function(row){return cb(row);});},
    gethydrotestVen       : function(data,cb){dbbase.gethydrotestVen(data,function(row){return cb(row);});},
    getPriceCompetitiveVen       : function(data,cb){dbbase.getPriceCompetitiveVen(data,function(row){return cb(row);});},
    getPriceCompetitiveEdit       : function(data,cb){dbbase.getPriceCompetitiveEdit(data,function(row){return cb(row);});},
    getForgingVen       : function(data,cb){dbbase.getForgingVen(data,function(row){return cb(row);});},
    getPurchaseOrderDetails       : function(data,cb){dbbase.getPurchaseOrderDetails(data,function(row){return cb(row);});},
    getNewPurchaseOrderDetails       : function(data,cb){dbbase.getNewPurchaseOrderDetails(data,function(row){return cb(row);});},
    getPurchaseOrderVen       : function(data,cb){dbbase.getPurchaseOrderVen(data,function(row){return cb(row);});},
    getPoDetails       : function(data,cb){dbbase.getPoDetails(data,function(row){return cb(row);});},
    getCusDetails       : function(data,cb){dbbase.getCusDetails(data,function(row){return cb(row);});},
    getPurchaseOrderEdit       : function(data,cb){dbbase.getPurchaseOrderEdit(data,function(row){return cb(row);});},
    getSpecialCompVen       : function(data,cb){dbbase.getSpecialCompVen(data,function(row){return cb(row);});},
    getofferMappingVen       : function(data,cb){dbbase.getofferMappingVen(data,function(row){return cb(row);});},
    getMappingdetailsByItemId       : function(data,cb){dbbase.getMappingdetailsByItemId(data,function(row){return cb(row);});},
    newMappingdetailsByItemId       : function(data,cb){dbbase.newMappingdetailsByItemId(data,function(row){return cb(row);});},
    getWOMappingVen       : function(data,cb){dbbase.getWOMappingVen(data,function(row){return cb(row);});},
    newWoMappingdetailsByItemId       : function(data,cb){dbbase.newWoMappingdetailsByItemId(data,function(row){return cb(row);});},
    getBillTermsDetail       : function(data,cb){dbbase.getBillTermsDetail(data,function(row){return cb(row);});},
    reportallpoDet       : function(data,cb){dbbase.reportallpoDet(data,function(row){return cb(row);});},
    reportpoDetByItem       : function(data,cb){dbbase.reportpoDetByItem(data,function(row){return cb(row);});},
    reportpoAdditional       : function(data,cb){dbbase.reportpoAdditional(data,function(row){return cb(row);});},
    getsubcodificationVen       : function(data,cb){dbbase.getsubcodificationVen(data,function(row){return cb(row);});},
    reportallAdditionsDet       : function(data,cb){dbbase.reportallAdditionsDet(data,function(row){return cb(row);});},
    getAssetSaleVen       : function(data,cb){dbbase.getAssetSaleVen(data,function(row){return cb(row);});},
    getSaleAssetEdit       : function(data,cb){dbbase.getSaleAssetEdit(data,function(row){return cb(row);});},
    reportallOpeningsDet       : function(data,cb){dbbase.reportallOpeningsDet(data,function(row){return cb(row);});},
    reportallpoDetByDeliveryDate       : function(data,cb){dbbase.reportallpoDetByDeliveryDate(data,function(row){return cb(row);});},
    getprodilist       : function(data,cb){dbbase.getprodilist(data,function(row){return cb(row);});},
    getspecialserviceVen       : function(data,cb){dbbase.getspecialserviceVen(data,function(row){return cb(row);});},
    getSubServiceVen       : function(data,cb){dbbase.getSubServiceVen(data,function(row){return cb(row);});},
    ckDuplicateEnquiry       : function(data,cb){dbbase.ckDuplicateEnquiry(data,function(row){return cb(row);});},
    getmaterialVen       : function(data,cb){dbbase.getmaterialVen(data,function(row){return cb(row);});},
    insertofferitemdetails       : function(data,cb){dbbase.insertofferitemdetails(data,function(row){return cb(row);});},
    getWoMappingdetailsByItemId       : function(data,cb){dbbase.getWoMappingdetailsByItemId(data,function(row){return cb(row);});},
    getTechnoCommercialworkorder       : function(data,cb){dbbase.getTechnoCommercialworkorder(data,function(row){return cb(row);});},
    getInspectionVen       : function(data,cb){dbbase.getInspectionVen(data,function(row){return cb(row);});},
    
    
    selectDb       : function(tbl,cnd,cb){dbbase.selectDb(tbl,cnd,function(row){return cb(row);});},
    updateDb       : function(tbl,data,cnd,cb){dbbase.updateDb(tbl,data,cnd,function(row){return cb(row);});},
    insertDb       : function(tbl,data,cb){dbbase.insertDb(tbl,data,function(row){return cb(row);});},
    selectCustomDb       : function(sql,cb){dbbase.selectCustomDb(sql,function(row){return cb(row);});},
    updateDbCustom       : function(tbl,data,cnd,cb){dbbase.updateDbCustom(tbl,data,cnd,function(row){return cb(row);});},
    deleteDb       : function(tbl,data,cb){dbbase.deleteDb(tbl,data,function(row){return cb(row);});},
    companySetup       : function(data){dbbase.companySetup(data);},
    
};

